var completed = [{ "name": "Glamour Dolls Makeup",
"complete": "complete",
"raised": 20725,
"timeRaised": 9,
"amountRaised": 61,
"timeReturned": 7.5,
"percentReturned": 14},
{ "name": "Mirage Pet Products",
"complete": "complete",
"raised": 20726,
"timeRaised": 720,
"amountRaised": 131,
"timeReturned": 6.5,
"percentReturned": 10},
{ "name": "Nada Bottle",
"complete": "complete",
"raised": 20518,
"timeRaised": 1440,
"amountRaised": 164,
"timeReturned": 7,
"percentReturned": 11},
{ "name": "Stojo",
"complete": "complete",
"raised": 24870,
"timeRaised": 1440,
"amountRaised": 166,
"timeReturned": 6.5,
"percentReturned": 12},
{ "name": "LorettaRose, LLC",
"complete": "complete",
"raised": 1036,
"timeRaised": 14,
"amountRaised": 18,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "ProjectorTeam Inc.",
"complete": "complete",
"raised": 11285,
"timeRaised": 120,
"amountRaised": 152,
"timeReturned": 3,
"percentReturned": 6},
{ "name": "Vaportini",
"complete": "complete",
"raised": 1039,
"timeRaised": 7,
"amountRaised": 80,
"timeReturned": 3,
"percentReturned": 5},
{ "name": "Imagiroo, LLC",
"complete": "complete",
"raised": 7679,
"timeRaised": 5,
"amountRaised": 34,
"timeReturned": 4.5,
"percentReturned": 10},
{ "name": "Plush Beez",
"complete": "complete",
"raised": 5181,
"timeRaised": 1440,
"amountRaised": 53,
"timeReturned": 6.5,
"percentReturned": 10},
{ "name": "Tosi Health",
"complete": "complete",
"raised": 10080,
"timeRaised": 7,
"amountRaised": 39,
"timeReturned": 3.5,
"percentReturned": 8},
{ "name": "GLOSS Moderne",
"complete": "complete",
"raised": 10873,
"amountRaised": 146,
"timeReturned": 3,
"percentReturned": 4},
{ "name": "Open Wire Lab LLC",
"complete": "complete",
"raised": 1969,
"timeRaised": 7,
"amountRaised": 29,
"timeReturned": 3.6,
"percentReturned": 8},
{ "name": "The Shrine",
"complete": "complete",
"raised": 25824,
"timeRaised": 7200,
"amountRaised": 217,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Jersey Shore Cosmetics,LLC",
"complete": "complete",
"raised": 6010,
"timeRaised": 7,
"amountRaised": 144,
"timeReturned": 2.3,
"percentReturned": 4},
{ "name": "Devils Due Entertainment",
"complete": "complete",
"raised": 11192,
"timeRaised": 21,
"amountRaised": 199,
"timeReturned": 4.5,
"percentReturned": 8},
{ "name": "Murbles",
"complete": "complete",
"raised": 1100,
"timeRaised": 10,
"amountRaised": 10,
"timeReturned": 3,
"percentReturned": 6},
{ "name": "Glomtom International LLC",
"complete": "complete",
"raised": 1036,
"timeRaised": 2,
"amountRaised": 44,
"timeReturned": 5,
"percentReturned": 10},
{ "name": "DIY Screen Printing Supplies",
"complete": "complete",
"raised": 6062,
"timeRaised": 300,
"amountRaised": 186,
"timeReturned": 6.6,
"percentReturned": 10},
{ "name": "Tuggo Dog Toys",
"complete": "complete",
"raised": 9948,
"timeRaised": 7,
"amountRaised": 179,
"timeReturned": 4.5,
"percentReturned": 20},
{ "name": "Madeleine Maternity",
"complete": "complete",
"raised": 10363,
"timeRaised": 10080,
"amountRaised": 52,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "North Coast Organics, LLC",
"complete": "complete",
"raised": 4415,
"timeRaised": 9,
"amountRaised": 67,
"timeReturned": 4,
"percentReturned": 8},
{ "name": "Dermo-Tech Inc",
"complete": "complete",
"raised": 10278,
"timeRaised": 180,
"amountRaised": 145,
"timeReturned": 7,
"percentReturned": 15},
{ "name": "Wild Mantle",
"complete": "complete",
"raised": 10446,
"timeRaised": 20160,
"amountRaised": 52,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "BrightFingers Inc.",
"complete": "complete",
"raised": 3114,
"timeRaised": 1140,
"amountRaised": 28,
"timeReturned": 3,
"percentReturned": 7},
{ "name": "Harvey Prince Organics",
"complete": "complete",
"raised": 10362,
"timeRaised": 20160,
"amountRaised": 126,
"timeReturned": 4,
"percentReturned": 7},
{ "name": "Craft Beer Hound",
"complete": "complete",
"raised": 4725,
"timeRaised": 10080,
"amountRaised": 39,
"timeReturned": 5.8,
"percentReturned": 10},
{ "name": "Cyclops Gear",
"complete": "complete",
"raised": 8808,
"timeRaised": 2880,
"amountRaised": 125,
"timeReturned": 2,
"percentReturned": 6},
{ "name": "Clarisea, Inc.",
"complete": "complete",
"raised": 9326,
"timeRaised": 1020,
"amountRaised": 63,
"timeReturned": 3,
"percentReturned": 8},
{ "name": "Phenoh Inc.",
"complete": "complete",
"raised": 10725,
"timeRaised": 20160,
"amountRaised": 55,
"timeReturned": 2,
"percentReturned": 5},
{ "name": "Slice, Inc",
"complete": "complete",
"raised": 10881,
"timeRaised": 2880,
"amountRaised": 71,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Rhetorical Factory",
"complete": "complete",
"raised": 1554,
"timeRaised": 10080,
"amountRaised": 23,
"timeReturned": 5,
"percentReturned": 9},
{ "name": "StoneBridge Imports",
"complete": "complete",
"raised": 9326,
"timeRaised": 7200,
"amountRaised": 93,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Cheapies Discount Store",
"complete": "complete",
"raised": 1013,
"timeRaised": 17,
"amountRaised": 88,
"timeReturned": 5,
"percentReturned": 11},
{ "name": "Skinny Tie Madness",
"complete": "complete",
"raised": 10363,
"timeRaised": 32,
"amountRaised": 208,
"timeReturned": 6,
"percentReturned": 20},
{ "name": "Koyono",
"complete": "complete",
"raised": 9689,
"timeRaised": 10080,
"amountRaised": 51,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "TITIN Tech",
"complete": "complete",
"raised": 10358,
"timeRaised": 540,
"amountRaised": 154,
"timeReturned": 1,
"percentReturned": 10},
{ "name": "Cantrip Games",
"complete": "complete",
"raised": 1036,
"timeRaised": 5760,
"amountRaised": 23,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Humanoid Wakeboards",
"complete": "complete",
"raised": 11399,
"timeRaised": 20160,
"amountRaised": 123,
"timeReturned": 3,
"percentReturned": 8},
{ "name": "North Coast Organics, LLC",
"complete": "complete",
"raised": 7063,
"timeRaised": 960,
"amountRaised": 67,
"timeReturned": 4,
"percentReturned": 8},
{ "name": "AMARA swimwear",
"complete": "complete",
"raised": 6839,
"timeRaised": 7200,
"amountRaised": 107,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Dont Blow The Illusion",
"complete": "complete",
"raised": 9326,
"timeRaised": 5760,
"amountRaised": 100,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Brute Force",
"complete": "complete",
"raised": 9623,
"timeRaised": 20160,
"amountRaised": 52,
"timeReturned": 3,
"percentReturned": 6},
{ "name": "The Mulberry Silk Co",
"complete": "complete",
"raised": 8859,
"timeRaised": 30240,
"amountRaised": 162,
"timeReturned": 4,
"percentReturned": 9},
{ "name": "Lawrence Hunt, LLC",
"complete": "complete",
"raised": 1865,
"timeRaised": 10080,
"amountRaised": 37,
"timeReturned": 5,
"percentReturned": 11},
{ "name": "RaveNectar",
"complete": "complete",
"raised": 9974,
"timeRaised": 2880,
"amountRaised": 69,
"timeReturned": 2,
"percentReturned": 8},
{ "name": "Plug & Feather",
"complete": "complete",
"raised": 3109,
"timeRaised": 5760,
"amountRaised": 31,
"timeReturned": 4,
"percentReturned": 10},
{ "name": "North Coast Organics, LLC",
"complete": "complete",
"raised": 1902,
"timeRaised": 10,
"amountRaised": 67,
"timeReturned": 2,
"percentReturned": 8},
{ "name": "MI OLA",
"complete": "complete",
"raised": 10446,
"timeRaised": 10080,
"amountRaised": 156,
"timeReturned": 4,
"percentReturned": 6},
{ "name": "Sparse",
"complete": "complete",
"raised": 7254,
"timeRaised": 30240,
"amountRaised": 29,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Allegory Handcrafted Goods",
"complete": "complete",
"raised": 11399,
"timeRaised": 10080,
"amountRaised": 61,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "CO.ALITION",
"complete": "complete",
"raised": 1411,
"timeRaised": 540,
"amountRaised": 152,
"timeReturned": 2,
"percentReturned": 7},
{ "name": "Wiplabs",
"complete": "complete",
"raised": 2329,
"timeRaised": 7200,
"amountRaised": 36,
"timeReturned": 3,
"percentReturned": 7},
{ "name": "North Coast Organics, LLC",
"complete": "complete",
"raised": 1503,
"timeRaised": 60,
"amountRaised": 67,
"timeReturned": 2,
"percentReturned": 10},
{ "name": "Marlie Madison",
"complete": "complete",
"raised": 4223,
"timeRaised": 4320,
"amountRaised": 112,
"timeReturned": 4,
"percentReturned": 8},
{ "name": "Marlie Madison",
"complete": "complete",
"raised": 2977,
"timeRaised": 5760,
"amountRaised": 112,
"timeReturned": 3,
"percentReturned": 10}
];
