var funded = [{ "name": "THIS IS A LOVE SONG LLC",
"complete": "funded",
"raised": 10519,
"timeRaised": 1,
"amountRaised": 52,
"timeReturned": 7,
"percentReturned": 10},
{ "name": "Activa Naturals Inc",
"complete": "funded",
"raised": 14249,
"timeRaised": 1,
"amountRaised": 47,
"timeReturned": 5,
"percentReturned": 10},
{ "name": "Aiwa",
"complete": "funded",
"raised": 23316,
"timeRaised": 1,
"amountRaised": 75,
"timeReturned": 7.3,
"percentReturned": 11},
{ "name": "Unlimited Cellular",
"complete": "funded",
"raised": 16477,
"timeRaised": 19,
"amountRaised": 107,
"timeReturned": 6.3,
"percentReturned": 8},
{ "name": "SnapLaces",
"complete": "funded",
"raised": 20883,
"timeRaised": 1,
"amountRaised": 65,
"timeReturned": 6.9,
"percentReturned": 12},
{ "name": "Silikids, Inc.",
"complete": "funded",
"raised": 36269,
"timeRaised": 1,
"amountRaised": 114,
"timeReturned": 7,
"percentReturned": 12},
{ "name": "Stojo",
"complete": "funded",
"raised": 65492,
"timeRaised": 1,
"amountRaised": 166,
"timeReturned": 8.5,
"percentReturned": 10},
{ "name": "Nada Bottle",
"complete": "funded",
"raised": 102591,
"timeRaised": 3,
"amountRaised": 164,
"timeReturned": 9.5,
"percentReturned": 12},
{ "name": "Devils Due Entertainment",
"complete": "funded",
"raised": 39767,
"timeRaised": 20160,
"amountRaised": 199,
"timeReturned": 7.5,
"percentReturned": 8},
{ "name": "Spicy Doodles Gaming Inc",
"complete": "funded",
"raised": 51813,
"timeRaised": 10080,
"amountRaised": 177,
"timeReturned": 9,
"percentReturned": 11},
{ "name": "Airbac ",
"complete": "funded",
"raised": 1057,
"timeRaised": 1,
"amountRaised": 20,
"timeReturned": 5,
"percentReturned": 10},
{ "name": "Proper Product Co.",
"complete": "funded",
"raised": 20245,
"timeRaised": 42,
"amountRaised": 73,
"timeReturned": 7,
"percentReturned": 10},
{ "name": "Alco Packaging Inc",
"complete": "funded",
"raised": 15399,
"timeRaised": 23,
"amountRaised": 48,
"timeReturned": 7.5,
"percentReturned": 10},
{ "name": "Buddha Babe",
"complete": "funded",
"raised": 7617,
"timeRaised": 60,
"amountRaised": 52,
"timeReturned": 8,
"percentReturned": 11},
{ "name": "mcSquares",
"complete": "funded",
"raised": 20746,
"timeRaised": 1,
"amountRaised": 59,
"timeReturned": 6.2,
"percentReturned": 15},
{ "name": "OlovesM",
"complete": "funded",
"raised": 2062,
"timeRaised": 1,
"amountRaised": 27,
"timeReturned": 6.5,
"percentReturned": 10},
{ "name": "Spinarri AutoSkewers Inc.",
"complete": "funded",
"raised": 4560,
"timeRaised": 2880,
"amountRaised": 52,
"timeReturned": 10,
"percentReturned": 11},
{ "name": "Cowbells.com",
"complete": "funded",
"raised": 3109,
"timeRaised": 1,
"amountRaised": 17,
"timeReturned": 4,
"percentReturned": 8},
{ "name": "ProjectorTeam Inc.",
"complete": "funded",
"raised": 31010,
"timeRaised": 4320,
"amountRaised": 152,
"timeReturned": 6.5,
"percentReturned": 9},
{ "name": "Ecocentric LTD",
"complete": "funded",
"raised": 33445,
"timeRaised": 4320,
"amountRaised": 159,
"timeReturned": 7,
"percentReturned": 11},
{ "name": "Conway Bikeboards, LLC",
"complete": "funded",
"raised": 10362,
"timeRaised": 1080,
"amountRaised": 56,
"timeReturned": 6.2,
"percentReturned": 10},
{ "name": "Paul Evans LLC",
"complete": "funded",
"raised": 31047,
"timeRaised": 960,
"amountRaised": 111,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Generation T",
"complete": "funded",
"raised": 4819,
"timeRaised": 13,
"amountRaised": 35,
"timeReturned": 2.5,
"percentReturned": 10},
{ "name": "Mirage Pet Products",
"complete": "funded",
"raised": 84249,
"timeRaised": 35,
"amountRaised": 131,
"timeReturned": 7,
"percentReturned": 10},
{ "name": "Art of Photography, LLC ",
"complete": "funded",
"raised": 4352,
"timeRaised": 960,
"amountRaised": 41,
"timeReturned": 7,
"percentReturned": 10},
{ "name": "L.A. Christine",
"complete": "funded",
"raised": 14767,
"timeRaised": 48,
"amountRaised": 85,
"timeReturned": 7.5,
"percentReturned": 13},
{ "name": "Out Of Warranty Inc",
"complete": "funded",
"raised": 13886,
"timeRaised": 540,
"amountRaised": 70,
"timeReturned": 5.3,
"percentReturned": 8},
{ "name": "MI OLA",
"complete": "funded",
"raised": 48717,
"amountRaised": 156,
"timeReturned": 9,
"percentReturned": 15},
{ "name": "DIY Screen Printing Supplies",
"complete": "funded",
"raised": 50776,
"amountRaised": 186,
"timeReturned": 9,
"percentReturned": 13},
{ "name": "Le Dame Footwear",
"complete": "funded",
"raised": 17411,
"timeRaised": 60,
"amountRaised": 60,
"timeReturned": 8,
"percentReturned": 14},
{ "name": "Devon Chase & Company",
"complete": "funded",
"raised": 10259,
"timeRaised": 1,
"amountRaised": 37,
"timeReturned": 4.7,
"percentReturned": 10},
{ "name": "The Shrine",
"complete": "funded",
"raised": 67358,
"timeRaised": 8640,
"amountRaised": 217,
"timeReturned": 10,
"percentReturned": 12},
{ "name": "Gardencense, LLC",
"complete": "funded",
"raised": 10933,
"timeRaised": 4320,
"amountRaised": 49,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Copper Tech ",
"complete": "funded",
"raised": 10363,
"timeRaised": 4320,
"amountRaised": 61,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "StoneBridge Imports",
"complete": "funded",
"raised": 10712,
"timeRaised": 1440,
"amountRaised": 93,
"timeReturned": 6.1,
"percentReturned": 9},
{ "name": "Skinny Tie Madness",
"complete": "funded",
"raised": 65285,
"timeRaised": 10080,
"amountRaised": 208,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Humanoid Wakeboards",
"complete": "funded",
"raised": 39606,
"timeRaised": 10080,
"amountRaised": 123,
"timeReturned": 7,
"percentReturned": 12},
{ "name": "Glomtom International LLC",
"complete": "funded",
"raised": 5181,
"timeRaised": 10,
"amountRaised": 44,
"timeReturned": 6,
"percentReturned": 9},
{ "name": "Zipz Shoes, Inc.",
"complete": "funded",
"raised": 41108,
"timeRaised": 4320,
"amountRaised": 91,
"timeReturned": 6,
"percentReturned": 11},
{ "name": "Jack and Jill Boutique",
"complete": "funded",
"raised": 9171,
"timeRaised": 10080,
"amountRaised": 53,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Rude American Bat Company",
"complete": "funded",
"raised": 26252,
"timeRaised": 5760,
"amountRaised": 93,
"timeReturned": 6,
"percentReturned": 12},
{ "name": "Sodo Apparel Inc.",
"complete": "funded",
"raised": 45273,
"timeRaised": 30,
"amountRaised": 77,
"timeReturned": 6,
"percentReturned": 12},
{ "name": "Elephant Coffee Importers, LLC",
"complete": "funded",
"raised": 41451,
"timeRaised": 5760,
"amountRaised": 139,
"timeReturned": 6,
"percentReturned": 12},
{ "name": "R.B. of McD INC.",
"complete": "funded",
"raised": 7637,
"timeRaised": 240,
"amountRaised": 39,
"timeReturned": 8,
"percentReturned": 15},
{ "name": "Risto Sports LLC",
"complete": "funded",
"raised": 12311,
"timeRaised": 10080,
"amountRaised": 94,
"timeReturned": 6.3,
"percentReturned": 10},
{ "name": "Motion Sound",
"complete": "funded",
"raised": 19050,
"timeRaised": 2880,
"amountRaised": 80,
"timeReturned": 6,
"percentReturned": 11},
{ "name": "CELSUS Bio-Intelligence",
"complete": "funded",
"raised": 1554,
"timeRaised": 1,
"amountRaised": 25,
"timeReturned": 5.6,
"percentReturned": 10},
{ "name": "VACADO LLC",
"complete": "funded",
"raised": 10446,
"timeRaised": 1,
"amountRaised": 25,
"timeReturned": 3,
"percentReturned": 10},
{ "name": "Jorel Parker",
"complete": "funded",
"raised": 18653,
"timeRaised": 1440,
"amountRaised": 74,
"timeReturned": 4.4,
"percentReturned": 7},
{ "name": "INNARAH INC",
"complete": "funded",
"raised": 37824,
"timeRaised": 1080,
"amountRaised": 131,
"timeReturned": 7.5,
"percentReturned": 12},
{ "name": "TITIN Tech",
"complete": "funded",
"raised": 74485,
"amountRaised": 154,
"timeReturned": 6.5,
"percentReturned": 8},
{ "name": "ARO",
"complete": "funded",
"raised": 5544,
"timeRaised": 55,
"amountRaised": 34,
"timeReturned": 6.1,
"percentReturned": 10},
{ "name": "Wellington & Cromwell",
"complete": "funded",
"raised": 12694,
"timeRaised": 1,
"amountRaised": 45,
"timeReturned": 5.2,
"percentReturned": 12},
{ "name": "PLANK Eyewear",
"complete": "funded",
"raised": 6140,
"timeRaised": 1380,
"amountRaised": 47,
"timeReturned": 7,
"percentReturned": 10},
{ "name": "Dermo-Tech Inc",
"complete": "funded",
"raised": 59482,
"timeRaised": 60,
"amountRaised": 145,
"timeReturned": 10,
"percentReturned": 13},
{ "name": "Walker Wear",
"complete": "funded",
"raised": 3770,
"timeRaised": 17,
"amountRaised": 40,
"timeReturned": 6.7,
"percentReturned": 10},
{ "name": "Sunny Paradise",
"complete": "funded",
"raised": 13243,
"amountRaised": 40,
"timeReturned": 4.5,
"percentReturned": 12},
{ "name": "Brain-Pad, Inc.",
"complete": "funded",
"raised": 20674,
"timeRaised": 21,
"amountRaised": 76,
"timeReturned": 5,
"percentReturned": 10},
{ "name": "Scratch Tracks",
"complete": "funded",
"raised": 7513,
"timeRaised": 10,
"amountRaised": 48,
"timeReturned": 5.5,
"percentReturned": 10},
{ "name": "Interstate Bait",
"complete": "funded",
"raised": 4663,
"amountRaised": 35,
"timeReturned": 3.7,
"percentReturned": 10},
{ "name": "Accent Wall Customs",
"complete": "funded",
"raised": 2073,
"amountRaised": 24,
"timeReturned": 3.2,
"percentReturned": 9},
{ "name": "359 Degrees LLC",
"complete": "funded",
"raised": 52076,
"timeRaised": 26,
"amountRaised": 88,
"timeReturned": 5,
"percentReturned": 12},
{ "name": "Planet Cowboy",
"complete": "funded",
"raised": 9637,
"timeRaised": 8640,
"amountRaised": 82,
"timeReturned": 8,
"percentReturned": 10},
{ "name": "Plush Beez",
"complete": "funded",
"raised": 5181,
"timeRaised": 1,
"amountRaised": 53,
"timeReturned": 6,
"percentReturned": 9},
{ "name": "Starboard Collection, LLC",
"complete": "funded",
"raised": 2436,
"timeRaised": 9,
"amountRaised": 30,
"timeReturned": 5,
"percentReturned": 10},
{ "name": "Radha Beauty Products, LLC",
"complete": "funded",
"raised": 51570,
"timeRaised": 7,
"amountRaised": 65,
"timeReturned": 5,
"percentReturned": 12},
{ "name": "McMarden",
"complete": "funded",
"raised": 6333,
"timeRaised": 2,
"amountRaised": 24,
"timeReturned": 7,
"percentReturned": 15},
{ "name": "PANYC State Apparel",
"complete": "funded",
"raised": 1793,
"timeRaised": 3,
"amountRaised": 81,
"timeReturned": 6.5,
"percentReturned": 10},
{ "name": "AMARA swimwear",
"complete": "funded",
"raised": 20725,
"timeRaised": 18,
"amountRaised": 107,
"timeReturned": 8,
"percentReturned": 12},
{ "name": "Juppy LLC",
"complete": "funded",
"raised": 8601,
"timeRaised": 12,
"amountRaised": 44,
"timeReturned": 9.3,
"percentReturned": 13},
{ "name": "Garayalde",
"complete": "funded",
"raised": 20722,
"timeRaised": 4320,
"amountRaised": 98,
"timeReturned": 6,
"percentReturned": 12},
{ "name": "HAUTEBUTCH, Inc",
"complete": "funded",
"raised": 19171,
"amountRaised": 78,
"timeReturned": 8,
"percentReturned": 12},
{ "name": "Dont Blow The Illusion",
"complete": "funded",
"raised": 13472,
"amountRaised": 100,
"timeReturned": 8,
"percentReturned": 10},
{ "name": "Lea Journo Cosmetique",
"complete": "funded",
"raised": 3930,
"timeRaised": 3,
"amountRaised": 32,
"timeReturned": 4.6,
"percentReturned": 10},
{ "name": "Clarisea, Inc.",
"complete": "funded",
"raised": 10363,
"timeRaised": 16,
"amountRaised": 63,
"timeReturned": 4.2,
"percentReturned": 9},
{ "name": "MM Local Foods, LLC",
"complete": "funded",
"raised": 21057,
"timeRaised": 6,
"amountRaised": 58,
"timeReturned": 6,
"percentReturned": 12},
{ "name": "Jersey Shore Cosmetics,LLC",
"complete": "funded",
"raised": 51813,
"timeRaised": 1440,
"amountRaised": 144,
"timeReturned": 8,
"percentReturned": 13},
{ "name": "Bellies to Babies",
"complete": "funded",
"raised": 1710,
"timeRaised": 1,
"amountRaised": 19,
"timeReturned": 4.8,
"percentReturned": 10},
{ "name": "Sweet Tea Factory, LLC",
"complete": "funded",
"raised": 8285,
"timeRaised": 31,
"amountRaised": 48,
"timeReturned": 6.7,
"percentReturned": 12},
{ "name": "Seventwentyfour LLC",
"complete": "funded",
"raised": 6269,
"timeRaised": 8640,
"amountRaised": 58,
"timeReturned": 6.7,
"percentReturned": 10},
{ "name": "Nori Lights",
"complete": "funded",
"raised": 19697,
"timeRaised": 8640,
"amountRaised": 104,
"timeReturned": 8,
"percentReturned": 12},
{ "name": "Nip and Bones",
"complete": "funded",
"raised": 7236,
"timeRaised": 10080,
"amountRaised": 32,
"timeReturned": 4.2,
"percentReturned": 20},
{ "name": "Tuggo Dog Toys",
"complete": "funded",
"raised": 68394,
"timeRaised": 10080,
"amountRaised": 179,
"timeReturned": 6.5,
"percentReturned": 13},
{ "name": "Panda Poles",
"complete": "funded",
"raised": 7254,
"timeRaised": 240,
"amountRaised": 46,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "GLOSS Moderne",
"complete": "funded",
"raised": 57202,
"timeRaised": 32,
"amountRaised": 146,
"timeReturned": 8,
"percentReturned": 15},
{ "name": "Kapture",
"complete": "funded",
"raised": 102041,
"timeRaised": 30240,
"amountRaised": 121,
"timeReturned": 8,
"percentReturned": 13},
{ "name": "Geekify Inc",
"complete": "funded",
"raised": 5803,
"timeRaised": 4,
"amountRaised": 26,
"timeReturned": 5,
"percentReturned": 12},
{ "name": "Jawbreaking",
"complete": "funded",
"raised": 23264,
"timeRaised": 60,
"amountRaised": 85,
"timeReturned": 5,
"percentReturned": 12},
{ "name": "BrewJacket, Inc.",
"complete": "funded",
"raised": 3109,
"timeRaised": 8,
"amountRaised": 28,
"timeReturned": 5,
"percentReturned": 10},
{ "name": "Company 19 LLC",
"complete": "funded",
"raised": 40181,
"amountRaised": 129,
"timeReturned": 6.7,
"percentReturned": 12},
{ "name": "Vaportini",
"complete": "funded",
"raised": 20294,
"timeRaised": 30,
"amountRaised": 80,
"timeReturned": 4,
"percentReturned": 9},
{ "name": "Green Arbor Clothing Co.",
"complete": "funded",
"raised": 10039,
"timeRaised": 240,
"amountRaised": 45,
"timeReturned": 7.2,
"percentReturned": 13},
{ "name": "GemPhones, Inc.",
"complete": "funded",
"raised": 8141,
"amountRaised": 91,
"timeReturned": 7,
"percentReturned": 12},
{ "name": "GameFaceGear LLC",
"complete": "funded",
"raised": 10334,
"amountRaised": 68,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "International Sports Fans",
"complete": "funded",
"raised": 12435,
"timeRaised": 5760,
"amountRaised": 78,
"timeReturned": 6.5,
"percentReturned": 10},
{ "name": "Cyclops Gear",
"complete": "funded",
"raised": 25534,
"timeRaised": 10080,
"amountRaised": 125,
"timeReturned": 5,
"percentReturned": 9},
{ "name": "Harvey Prince Organics",
"complete": "funded",
"raised": 39378,
"timeRaised": 1440,
"amountRaised": 126,
"timeReturned": 4.5,
"percentReturned": 8},
{ "name": "SWEET REBEL",
"complete": "funded",
"raised": 5053,
"timeRaised": 480,
"amountRaised": 32,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Boingo Baby",
"complete": "funded",
"raised": 17772,
"timeRaised": 1380,
"amountRaised": 80,
"timeReturned": 8,
"percentReturned": 15},
{ "name": "Baboon Bamboo",
"complete": "funded",
"raised": 10959,
"timeRaised": 8,
"amountRaised": 41,
"timeReturned": 6,
"percentReturned": 15},
{ "name": "The Mulberry Silk Co",
"complete": "funded",
"raised": 20537,
"amountRaised": 162,
"timeReturned": 6.8,
"percentReturned": 9},
{ "name": "Active Formulations, Inc.",
"complete": "funded",
"raised": 8459,
"timeRaised": 360,
"amountRaised": 52,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Pendulum Golf of Georgia LLC",
"complete": "funded",
"raised": 3109,
"timeRaised": 7,
"amountRaised": 23,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Yumms!",
"complete": "funded",
"raised": 9052,
"timeRaised": 10080,
"amountRaised": 65,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Es Closet",
"complete": "funded",
"raised": 9223,
"timeRaised": 180,
"amountRaised": 50,
"timeReturned": 7,
"percentReturned": 11},
{ "name": "Ecocise Bamboo Clothes",
"complete": "funded",
"raised": 5907,
"timeRaised": 40,
"amountRaised": 45,
"timeReturned": 5,
"percentReturned": 8},
{ "name": "LuMESH ",
"complete": "funded",
"raised": 10547,
"amountRaised": 53,
"timeReturned": 7,
"percentReturned": 13},
{ "name": "WILLACY ",
"complete": "funded",
"raised": 15544,
"timeRaised": 6,
"amountRaised": 35,
"timeReturned": 6,
"percentReturned": 15},
{ "name": "My Little Vixen LLC",
"complete": "funded",
"raised": 3109,
"timeRaised": 25,
"amountRaised": 24,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "Kayson Golf Ltd.",
"complete": "funded",
"raised": 3109,
"timeRaised": 120,
"amountRaised": 27,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "GreenerStep",
"complete": "funded",
"raised": 933,
"timeRaised": 6,
"amountRaised": 25,
"timeReturned": 6,
"percentReturned": 15},
{ "name": "Cheapies Discount Store",
"complete": "funded",
"raised": 22506,
"timeRaised": 420,
"amountRaised": 88,
"timeReturned": 8,
"percentReturned": 10},
{ "name": "Comic Book Displays",
"complete": "funded",
"raised": 9430,
"timeRaised": 60,
"amountRaised": 44,
"timeReturned": 4.7,
"percentReturned": 8},
{ "name": "CO.ALITION",
"complete": "funded",
"raised": 39488,
"amountRaised": 152,
"timeReturned": 12,
"percentReturned": 15},
{ "name": "Geometrical Inc.",
"complete": "funded",
"raised": 8549,
"timeRaised": 60,
"amountRaised": 127,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "American Dog",
"complete": "funded",
"raised": 10775,
"timeRaised": 1440,
"amountRaised": 52,
"timeReturned": 4,
"percentReturned": 8},
{ "name": "Leggage",
"complete": "funded",
"raised": 5044,
"timeRaised": 10080,
"amountRaised": 61,
"timeReturned": 6,
"percentReturned": 11},
{ "name": "Snow Lizard Products",
"complete": "funded",
"raised": 9119,
"timeRaised": 20160,
"amountRaised": 63,
"timeReturned": 4,
"percentReturned": 8},
{ "name": "Marlie Madison",
"complete": "funded",
"raised": 12396,
"timeRaised": 1200,
"amountRaised": 112,
"timeReturned": 6,
"percentReturned": 11},
{ "name": "Chesstache",
"complete": "funded",
"raised": 3648,
"timeRaised": 10080,
"amountRaised": 51,
"timeReturned": 6,
"percentReturned": 10},
{ "name": "THUMP",
"complete": "funded",
"raised": 9999,
"timeRaised": 10080,
"amountRaised": 50,
"timeReturned": 4,
"percentReturned": 7}];
